# Generated by Django 4.1.4 on 2023-02-09 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=35)),
                ('surname', models.CharField(default='', max_length=35)),
                ('address', models.CharField(default='', max_length=100)),
                ('telephone', models.CharField(default='', max_length=10)),
                ('gender', models.BooleanField(default=True)),
                ('carreer', models.CharField(default='', max_length=35)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('gid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=35)),
                ('brand', models.CharField(default='', max_length=35)),
                ('model', models.CharField(default='', max_length=35)),
                ('price', models.FloatField(default=0.0)),
                ('net', models.IntegerField(default=0)),
                ('property', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc_name', models.CharField(default='', max_length=35)),
                ('desc', models.CharField(default='', max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='', max_length=1)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.customer')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=0)),
                ('goods', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.goods')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.order')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goodscategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.goodscategory'),
        ),
    ]
